export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  BET_LOCK = 'BET_LOCK',
  BET_RELEASE = 'BET_RELEASE',
  WIN_CREDIT = 'WIN_CREDIT',
  COMMISSION = 'COMMISSION',
  WITHDRAW_REQUEST = 'WITHDRAW_REQUEST',
  WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS',
  PENALTY = 'PENALTY',
}

export enum GameStatus {
  WAITING = 'WAITING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MatchmakingStatus {
  SEARCHING = 'SEARCHING',
  MATCHED = 'MATCHED',
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT',
}

export enum WithdrawalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
}

export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
}

export enum FraudAlertType {
  COLLUSION = 'COLLUSION',
  ABNORMAL_WIN_RATIO = 'ABNORMAL_WIN_RATIO',
  EMULATOR_DETECTED = 'EMULATOR_DETECTED',
  ROOTED_DEVICE = 'ROOTED_DEVICE',
  MULTIPLE_ACCOUNTS = 'MULTIPLE_ACCOUNTS',
}

export enum FraudAlertStatus {
  FLAGGED = 'FLAGGED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CLEARED = 'CLEARED',
  CONFIRMED = 'CONFIRMED',
}
